# Generated by Django 2.2.14 on 2021-10-09 16:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211008_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='md_content',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
